apiVersion: v1
kind: Namespace
metadata:
  name: lab-kcr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-kcr
  namespace: lab-kcr
  labels:
    app: backend-nest-kcr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-kcr
  template:
    metadata:
      labels:
        app: backend-nest-kcr
    spec:
      containers:
      - name: backend-nest-kcr
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend_ncanales
        imagePullPolicy: Always